import json
import os
import threading
import time
import logging
import sqlite3
import random
import shutil
import subprocess
from json import JSONDecodeError
from datetime import datetime, date, timezone, timedelta
from config import DEVELOPER_ID, DATA_KEYS, DATABASE_PATH, DATABASE_URL, BACKUP_PATH

# Iraq currently observes UTC+03:00 year-round; a built-in timezone keeps the
# project compatible with the Python version used by older local deployments.
IRAQ_TZ = timezone(timedelta(hours=3), name='Asia/Baghdad')

class Database:
    def __init__(self):
        self.data_keys = DATA_KEYS
        self._lock = threading.RLock()
        self.database_path = DATABASE_PATH
        self.database_url = DATABASE_URL
        self.backup_path = BACKUP_PATH
        self._backend = 'postgresql' if self.database_url else 'sqlite'
        self._connection = self._connect_database()
        self._execute('CREATE TABLE IF NOT EXISTS app_data (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL)')
        self._connection.commit()
        self.create_files()
        self.insert_default_data()
        self._create_relational_schema()
        self._migrate_legacy_data()

        self._last_comment_ts = {}
        logging.basicConfig(level=logging.INFO)

    def _create_relational_schema(self):
        """Create the normalized read model without deleting legacy data.

        ``app_data`` is retained solely as a migration source and compatibility
        layer for the Telegram bot.  Every statement is idempotent, so an
        interrupted deploy can safely be started again.
        """
        identity = 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' if self._backend == 'postgresql' else 'INTEGER PRIMARY KEY'
        statements = [
            '''CREATE TABLE IF NOT EXISTS users (telegram_id BIGINT PRIMARY KEY, username TEXT, first_name TEXT, last_name TEXT, joined_at TEXT NOT NULL, last_active TEXT NOT NULL, is_banned INTEGER NOT NULL DEFAULT 0 CHECK(is_banned IN (0,1)))''',
            '''CREATE TABLE IF NOT EXISTS student_profiles (telegram_id BIGINT PRIMARY KEY REFERENCES users(telegram_id) ON DELETE CASCADE, full_name TEXT NOT NULL, stage INTEGER NOT NULL CHECK(stage BETWEEN 1 AND 4), registered_at TEXT NOT NULL)''',
            '''CREATE TABLE IF NOT EXISTS subjects (stage INTEGER NOT NULL CHECK(stage BETWEEN 1 AND 4), subject_key TEXT NOT NULL, name_ar TEXT NOT NULL, name_en TEXT, category TEXT NOT NULL, PRIMARY KEY(stage, subject_key))''',
            f'''CREATE TABLE IF NOT EXISTS content (id {identity}, stage INTEGER NOT NULL CHECK(stage BETWEEN 1 AND 4), subject_key TEXT NOT NULL, chapter INTEGER NOT NULL CHECK(chapter BETWEEN 1 AND 6), content_type TEXT NOT NULL, file_id TEXT, file_name TEXT, body TEXT, description TEXT, content_number INTEGER NOT NULL, added_by BIGINT, storage_message_id BIGINT, UNIQUE(stage, subject_key, chapter, content_number), FOREIGN KEY(stage, subject_key) REFERENCES subjects(stage, subject_key))''',
            f'''CREATE TABLE IF NOT EXISTS support_tickets (id {identity}, telegram_id BIGINT NOT NULL REFERENCES users(telegram_id), stage INTEGER NOT NULL CHECK(stage BETWEEN 1 AND 4), message TEXT NOT NULL, created_at TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open')''',
            f'''CREATE TABLE IF NOT EXISTS comments (id {identity}, telegram_id BIGINT NOT NULL REFERENCES users(telegram_id), content_id BIGINT NOT NULL REFERENCES content(id) ON DELETE CASCADE, stage INTEGER NOT NULL CHECK(stage BETWEEN 1 AND 4), body TEXT NOT NULL, created_at TEXT NOT NULL)''',
            '''CREATE TABLE IF NOT EXISTS favorites (telegram_id BIGINT NOT NULL REFERENCES users(telegram_id) ON DELETE CASCADE, content_id BIGINT NOT NULL REFERENCES content(id) ON DELETE CASCADE, created_at TEXT NOT NULL, PRIMARY KEY(telegram_id, content_id))''',
            '''CREATE TABLE IF NOT EXISTS quizzes (id BIGINT PRIMARY KEY, stage INTEGER NOT NULL CHECK(stage BETWEEN 1 AND 4), subject_key TEXT, question TEXT NOT NULL, options_json TEXT NOT NULL, correct_index INTEGER NOT NULL CHECK(correct_index >= 0), enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN (0,1)), added_by BIGINT, created_at TEXT NOT NULL)''',
            '''CREATE TABLE IF NOT EXISTS quiz_attempts (id BIGINT PRIMARY KEY, telegram_id BIGINT NOT NULL REFERENCES users(telegram_id), quiz_id BIGINT NOT NULL REFERENCES quizzes(id), answer_index INTEGER NOT NULL, is_correct INTEGER NOT NULL CHECK(is_correct IN (0,1)), attempted_at TEXT NOT NULL)''',
            '''CREATE TABLE IF NOT EXISTS schema_migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)''',
            'CREATE INDEX IF NOT EXISTS idx_content_stage_subject_chapter ON content(stage, subject_key, chapter)',
            'CREATE INDEX IF NOT EXISTS idx_content_search ON content(stage, description)',
            'CREATE INDEX IF NOT EXISTS idx_comments_content_created ON comments(content_id, created_at)',
            'CREATE INDEX IF NOT EXISTS idx_tickets_user_created ON support_tickets(telegram_id, created_at)',
        ]
        with self._lock:
            for statement in statements:
                self._execute(statement)
            self._connection.commit()

    def _migration_done(self, name):
        return bool(self._execute('SELECT 1 FROM schema_migrations WHERE name = ?', (name,)).fetchone())

    def _migration_mark(self, name):
        self._execute('INSERT INTO schema_migrations(name, applied_at) VALUES (?, ?)', (name, datetime.now(IRAQ_TZ).isoformat()))

    def _migrate_legacy_data(self):
        """Copy legacy JSON records once, transactionally, into normalized tables."""
        name = 'legacy_json_to_relational_v1'
        if self._migration_done(name):
            return
        try:
            with self._lock:
                users = {item.get('user_id'): item for item in self._read_data('users') if item.get('user_id')}
                stages = {item.get('user_id'): item for item in self._read_data('users_stages') if item.get('user_id')}
                now = datetime.now(IRAQ_TZ).isoformat()
                for uid, item in users.items():
                    self._execute('INSERT INTO users(telegram_id, username, first_name, last_name, joined_at, last_active, is_banned) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(telegram_id) DO NOTHING', (uid, item.get('username'), item.get('first_name'), item.get('last_name'), item.get('date_joined', now), item.get('last_active', now), int(bool(item.get('is_banned')))))
                for uid, item in stages.items():
                    if uid in users:
                        self._execute('INSERT INTO student_profiles(telegram_id, full_name, stage, registered_at) VALUES (?, ?, ?, ?) ON CONFLICT(telegram_id) DO NOTHING', (uid, item.get('full_name', ''), item.get('stage'), item.get('date_registered', now)))
                for item in self._read_data('subjects'):
                    self._execute('INSERT INTO subjects(stage, subject_key, name_ar, name_en, category) VALUES (?, ?, ?, ?, ?) ON CONFLICT(stage, subject_key) DO NOTHING', (item['stage'], item['key'], item['name_ar'], item.get('name_en'), item['category']))
                for item in self._read_data('stage_content'):
                    self._execute('INSERT INTO content(id, stage, subject_key, chapter, content_type, file_id, file_name, body, description, content_number, added_by, storage_message_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO NOTHING', (item['id'], item['stage'], item['subject_key'], item['chapter_num'], item['content_type'], item.get('file_id'), item.get('file_name'), item.get('text'), item.get('description'), item.get('content_number', item['id']), item.get('added_by'), item.get('storage_message_id')))
                for item in self._read_data('support_tickets'):
                    if item.get('user_id') in users:
                        self._execute('INSERT INTO support_tickets(id, telegram_id, stage, message, created_at, status) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO NOTHING', (item['id'], item['user_id'], item['stage'], item['message'], item.get('timestamp', now), item.get('status', 'open')))
                for item in self._read_data('comments'):
                    if item.get('user_id') in users:
                        self._execute('INSERT INTO comments(id, telegram_id, content_id, stage, body, created_at) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(id) DO NOTHING', (item['id'], item['user_id'], item['content_id'], item.get('stage', 1), item['text'], item.get('timestamp', now)))
                self._migration_mark(name)
                self._connection.commit()
            logging.info('Completed relational migration %s', name)
        except Exception:
            self._connection.rollback()
            logging.exception('Relational migration failed; legacy app_data was left intact')
            raise

    def _connect_database(self):
        if self._backend == 'postgresql':
            import psycopg
            return psycopg.connect(self.database_url, connect_timeout=15)
        os.makedirs(os.path.dirname(os.path.abspath(self.database_path)), exist_ok=True)
        connection = sqlite3.connect(self.database_path, check_same_thread=False)
        connection.execute('PRAGMA journal_mode=WAL')
        connection.execute('PRAGMA synchronous=NORMAL')
        return connection

    def _execute(self, query, params=()):
        if getattr(self._connection, 'closed', False):
            self._connection = self._connect_database()
        if self._backend == 'postgresql':
            query = query.replace('?', '%s')
        return self._connection.execute(query, params)

    def create_files(self):
        """تهيئة مجموعات البيانات داخل SQLite."""
        for key in self.data_keys:
            existing = self._execute('SELECT 1 FROM app_data WHERE key = ?', (key,)).fetchone()
            if existing:
                continue
            default = self._default_value(key)
            self._safe_write(key, default)

    def _default_value(self, key):
        if key in ('settings', 'comments_meta', 'ai_usage', 'notification_preferences'):
            return {}
        return []

    def insert_default_data(self):
        """إدخال البيانات الافتراضية (المواد، المطور، إعدادات الذكاء الاصطناعي)"""
        all_subjects = [
            (1, 'الرياضيات', 'mathematics', 'mathematics', 'subjects'),
            (1, 'اللغة العربية', 'arabic', 'arabic', 'subjects'),
            (1, 'اللغة الانجليزية', 'english', 'english', 'subjects'),
            (1, 'الحراره وخواص المادة', 'heat_material', 'heat_material', 'subjects'),
            (1, 'الكهربائية', 'electricity', 'electricity', 'subjects'),
            (1, 'اصول التربية', 'education_principles', 'education_principles', 'subjects'),
            (1, 'علم النفس', 'psychology', 'psychology', 'subjects'),
            (1, 'المكانيك', 'mechanics', 'mechanics', 'subjects'),
            (1, 'الحقوق والديمقراطية', 'rights_democracy', 'rights_democracy', 'subjects'),
            (1, 'الحاسوب', 'computer', 'computer', 'subjects'),

            (1, 'شرح الرياضيات', 'mathematics_exp', 'mathematics_exp', 'explanations'),
            (1, 'شرح اللغة العربية', 'arabic_exp', 'arabic_exp', 'explanations'),
            (1, 'شرح اللغة الانجليزية', 'english_exp', 'english_exp', 'explanations'),
            (1, 'شرح الحراره وخواص المادة', 'heat_material_exp', 'heat_material_exp', 'explanations'),
            (1, 'شرح الكهربائية', 'electricity_exp', 'electricity_exp', 'explanations'),
            (1, 'شرح اصول التربية', 'education_principles_exp', 'education_principles_exp', 'explanations'),
            (1, 'شرح علم النفس', 'psychology_exp', 'psychology_exp', 'explanations'),
            (1, 'شرح المكانيك', 'mechanics_exp', 'mechanics_exp', 'explanations'),
            (1, 'شرح الحقوق والديمقراطية', 'rights_democracy_exp', 'rights_democracy_exp', 'explanations'),
            (1, 'شرح الحاسوب', 'computer_exp', 'computer_exp', 'explanations'),

            (1, 'مختبر الميكانيك', 'mechanics_lab', 'mechanics_lab', 'lab'),
            (1, 'مختبر الكهربائية', 'electricity_lab', 'electricity_lab', 'lab'),
            (1, 'مختبر الحاسبات', 'computers_lab', 'computers_lab', 'lab'),

            (1, 'امتحان الرياضيات', 'mathematics_exam', 'mathematics_exam', 'exams'),
            (1, 'امتحان اللغة العربية', 'arabic_exam', 'arabic_exam', 'exams'),
            (1, 'امتحان اللغة الانجليزية', 'english_exam', 'english_exam', 'exams'),
            (1, 'امتحان الحراره وخواص المادة', 'heat_material_exam', 'heat_material_exam', 'exams'),
            (1, 'امتحان الكهربائية', 'electricity_exam', 'electricity_exam', 'exams'),
            (1, 'امتحان اصول التربية', 'education_principles_exam', 'education_principles_exam', 'exams'),
            (1, 'امتحان علم النفس', 'psychology_exam', 'psychology_exam', 'exams'),
            (1, 'امتحان المكانيك', 'mechanics_exam', 'mechanics_exam', 'exams'),
            (1, 'امتحان الحقوق والديمقراطية', 'rights_democracy_exam', 'rights_democracy_exam', 'exams'),
            (1, 'امتحان الحاسوب', 'computer_exam', 'computer_exam', 'exams'),

            (2, 'الرياضيات', 'mathematics', 'mathematics', 'subjects'),
            (2, 'الفلك', 'astronomy', 'astronomy', 'subjects'),
            (2, 'جرائم البعث', 'baath_crimes', 'baath_crimes', 'subjects'),
            (2, 'الصوت', 'sound', 'sound', 'subjects'),
            (2, 'الكهربائية', 'electricity', 'electricity', 'subjects'),
            (2, 'البصريات', 'optics', 'optics', 'subjects'),
            (2, 'الانكليزية', 'english', 'english', 'subjects'),
            (2, 'عربي', 'arabic', 'arabic', 'subjects'),
            (2, 'حاسبات', 'computer', 'computer', 'subjects'),
            (2, 'الادارة', 'management', 'management', 'subjects'),
            (2, 'تعليم التفكير', 'thinking_education', 'thinking_education', 'subjects'),
            (2, 'المنهج والبحث العلمي', 'curriculum_research', 'curriculum_research', 'subjects'),

            (2, 'شرح الرياضيات', 'mathematics_exp', 'mathematics_exp', 'explanations'),
            (2, 'شرح الفلك', 'astronomy_exp', 'astronomy_exp', 'explanations'),
            (2, 'شرح جرائم البعث', 'baath_crimes_exp', 'baath_crimes_exp', 'explanations'),
            (2, 'شرح الصوت', 'sound_exp', 'sound_exp', 'explanations'),
            (2, 'شرح الكهربائية', 'electricity_exp', 'electricity_exp', 'explanations'),
            (2, 'شرح البصريات', 'optics_exp', 'optics_exp', 'explanations'),
            (2, 'شرح الانكليزية', 'english_exp', 'english_exp', 'explanations'),
            (2, 'شرح عربي', 'arabic_exp', 'arabic_exp', 'explanations'),
            (2, 'شرح حاسبات', 'computer_exp', 'computer_exp', 'explanations'),
            (2, 'شرح الادارة', 'management_exp', 'management_exp', 'explanations'),
            (2, 'شرح تعليم التفكير', 'thinking_education_exp', 'thinking_education_exp', 'explanations'),
            (2, 'شرح المنهج والبحث العلمي', 'curriculum_research_exp', 'curriculum_research_exp', 'explanations'),

            (2, 'مختبر البرمجة', 'programming_lab', 'programming_lab', 'lab'),
            (2, 'مختبر الكهربائية', 'electricity_lab', 'electricity_lab', 'lab'),
            (2, 'مختبر البصريات', 'optics_lab', 'optics_lab', 'lab'),

            (2, 'امتحان الرياضيات', 'mathematics_exam', 'mathematics_exam', 'exams'),
            (2, 'امتحان الفلك', 'astronomy_exam', 'astronomy_exam', 'exams'),
            (2, 'امتحان جرائم البعث', 'baath_crimes_exam', 'baath_crimes_exam', 'exams'),
            (2, 'امتحان الصوت', 'sound_exam', 'sound_exam', 'exams'),
            (2, 'امتحان الكهربائية', 'electricity_exam', 'electricity_exam', 'exams'),
            (2, 'امتحان البصريات', 'optics_exam', 'optics_exam', 'exams'),
            (2, 'امتحان الانكليزية', 'english_exam', 'english_exam', 'exams'),
            (2, 'امتحان عربي', 'arabic_exam', 'arabic_exam', 'exams'),
            (2, 'امتحان حاسبات', 'computer_exam', 'computer_exam', 'exams'),
            (2, 'امتحان الادارة', 'management_exam', 'management_exam', 'exams'),
            (2, 'امتحان تعليم التفكير', 'thinking_education_exam', 'thinking_education_exam', 'exams'),
            (2, 'امتحان المنهج والبحث العلمي', 'curriculum_research_exam', 'curriculum_research_exam', 'exams'),

            (3, 'الدوال العقدية', 'complex_functions', 'complex_functions', 'subjects'),
            (3, 'الفيزياء الذرية', 'atomic_physics', 'atomic_physics', 'subjects'),
            (3, 'الالكترونيات', 'electronics', 'electronics', 'subjects'),
            (3, 'الثرموداينمك', 'thermodynamics', 'thermodynamics', 'subjects'),
            (3, 'مناهج وطرق التدريس', 'teaching_methods', 'teaching_methods', 'subjects'),
            (3, 'الارشاد التربوي', 'educational_guidance', 'educational_guidance', 'subjects'),
            (3, 'الميكانيك المتقدم', 'advanced_mechanics', 'advanced_mechanics', 'subjects'),
            (3, 'الانواء الجوية', 'meteorology', 'meteorology', 'subjects'),

            (3, 'شرح الدوال العقدية', 'complex_functions_exp', 'complex_functions_exp', 'explanations'),
            (3, 'شرح الفيزياء الذرية', 'atomic_physics_exp', 'atomic_physics_exp', 'explanations'),
            (3, 'شرح الالكترونيات', 'electronics_exp', 'electronics_exp', 'explanations'),
            (3, 'شرح الثرموداينمك', 'thermodynamics_exp', 'thermodynamics_exp', 'explanations'),
            (3, 'شرح مناهج وطرق التدريس', 'teaching_methods_exp', 'teaching_methods_exp', 'explanations'),
            (3, 'شرح الارشاد التربوي', 'educational_guidance_exp', 'educational_guidance_exp', 'explanations'),
            (3, 'شرح الميكانيك المتقدم', 'advanced_mechanics_exp', 'advanced_mechanics_exp', 'explanations'),
            (3, 'شرح الانواء الجوية', 'meteorology_exp', 'meteorology_exp', 'explanations'),

            (3, 'مختبر الالكترونيات', 'electronics_lab', 'electronics_lab', 'lab'),
            (3, 'مختبر الذرية', 'atomic_lab', 'atomic_lab', 'lab'),

            (3, 'امتحان الدوال العقدية', 'complex_functions_exam', 'complex_functions_exam', 'exams'),
            (3, 'امتحان الفيزياء الذرية', 'atomic_physics_exam', 'atomic_physics_exam', 'exams'),
            (3, 'امتحان الالكترونيات', 'electronics_exam', 'electronics_exam', 'exams'),
            (3, 'امتحان الثرموداينمك', 'thermodynamics_exam', 'thermodynamics_exam', 'exams'),
            (3, 'امتحان مناهج وطرق التدريس', 'teaching_methods_exam', 'teaching_methods_exam', 'exams'),
            (3, 'امتحان الارشاد التربوي', 'educational_guidance_exam', 'educational_guidance_exam', 'exams'),
            (3, 'امتحان الميكانيك المتقدم', 'advanced_mechanics_exam', 'advanced_mechanics_exam', 'exams'),
            (3, 'امتحان الانواء الجوية', 'meteorology_exam', 'meteorology_exam', 'exams'),

            (4, 'الميكانيك الكمي', 'quantum_mechanics', 'quantum_mechanics', 'subjects'),
            (4, 'الفيزياء الصلبة', 'solid_state_physics', 'solid_state_physics', 'subjects'),
            (4, 'الفيزياء النووية', 'nuclear_physics', 'nuclear_physics', 'subjects'),
            (4, 'الليزر', 'laser', 'laser', 'subjects'),
            (4, 'الكهرومغناطيسية', 'electromagnetism', 'electromagnetism', 'subjects'),
            (4, 'التربية العملية', 'practical_education', 'practical_education', 'subjects'),
            (4, 'القياس والتقويم', 'measurement_evaluation', 'measurement_evaluation', 'subjects'),

            (4, 'شرح الميكانيك الكمي', 'quantum_mechanics_exp', 'quantum_mechanics_exp', 'explanations'),
            (4, 'شرح الفيزياء الصلبة', 'solid_state_physics_exp', 'solid_state_physics_exp', 'explanations'),
            (4, 'شرح الفيزياء النووية', 'nuclear_physics_exp', 'nuclear_physics_exp', 'explanations'),
            (4, 'شرح الليزر', 'laser_exp', 'laser_exp', 'explanations'),
            (4, 'شرح الكهرومغناطيسية', 'electromagnetism_exp', 'electromagnetism_exp', 'explanations'),
            (4, 'شرح التربية العملية', 'practical_education_exp', 'practical_education_exp', 'explanations'),
            (4, 'شرح القياس والتقويم', 'measurement_evaluation_exp', 'measurement_evaluation_exp', 'explanations'),

            (4, 'مختبر الميكانيك الكمي', 'quantum_mechanics_lab', 'quantum_mechanics_lab', 'lab'),
            (4, 'مختبر الفيزياء النووية', 'nuclear_physics_lab', 'nuclear_physics_lab', 'lab'),
            (4, 'مختبر الليزر', 'laser_lab', 'laser_lab', 'lab'),

            (4, 'امتحان الميكانيك الكمي', 'quantum_mechanics_exam', 'quantum_mechanics_exam', 'exams'),
            (4, 'امتحان الفيزياء الصلبة', 'solid_state_physics_exam', 'solid_state_physics_exam', 'exams'),
            (4, 'امتحان الفيزياء النووية', 'nuclear_physics_exam', 'nuclear_physics_exam', 'exams'),
            (4, 'امتحان الليزر', 'laser_exam', 'laser_exam', 'exams'),
            (4, 'امتحان الكهرومغناطيسية', 'electromagnetism_exam', 'electromagnetism_exam', 'exams'),
            (4, 'امتحان التربية العملية', 'practical_education_exam', 'practical_education_exam', 'exams'),
            (4, 'امتحان القياس والتقويم', 'measurement_evaluation_exam', 'measurement_evaluation_exam', 'exams'),

            (4, 'البحث', 'physics_research', 'physics_research', 'research'),
            (4, 'المشاهدة', 'mathematics_research', 'mathematics_research', 'research'),
            (4, 'التطبيق ', 'computer_research', 'computer_research', 'research')
        ]

        exam_subjects = [subject for subject in all_subjects if subject[4] == 'exams']
        all_subjects = [subject for subject in all_subjects if subject[4] != 'exams']
        for stage, name_ar, name_en, key, _ in exam_subjects:
            base_key = key[:-5] if key.endswith('_exam') else key
            all_subjects.extend([
                (stage, name_ar, f'{name_en}_monthly', f'{base_key}_monthly_exam', 'monthly_exams'),
                (stage, name_ar, f'{name_en}_final', f'{base_key}_final_exam', 'final_exams'),
            ])

        subjects_data = []
        for subject in all_subjects:
            subjects_data.append({
                'stage': subject[0],
                'name_ar': subject[1],
                'name_en': subject[2],
                'key': subject[3],
                'category': subject[4]
            })
        current_subjects = self._read_data('subjects')
        if not current_subjects:
            self._write_data('subjects', subjects_data)

        admins = self._read_data('admins')
        if not any(a.get('user_id') == DEVELOPER_ID for a in admins):
            admins.append({
                'user_id': DEVELOPER_ID,
                'username': 'shahm41',
                'full_name': 'عباس غزوان عبد',
                'date_added': datetime.now().isoformat(),
                'added_by': DEVELOPER_ID
            })
            self._write_data('admins', admins)

    def _read_data(self, key):
        """قراءة البيانات من SQLite."""
        with self._lock:
            row = self._execute('SELECT value FROM app_data WHERE key = ?', (key,)).fetchone()
            if not row:
                default = self._default_value(key)
                self._safe_write(key, default)
                return default
            try:
                return json.loads(row[0])
            except (TypeError, JSONDecodeError):
                return self._default_value(key)

    def _safe_write(self, key, data, retries: int = 3, delay: float = 0.1):
        """كتابة ذرية في SQLite مع إعادة المحاولة."""
        encoded = json.dumps(data, ensure_ascii=False)
        for attempt in range(retries):
            try:
                with self._lock:
                    self._execute(
                        'INSERT INTO app_data(key, value, updated_at) VALUES (?, ?, ?) '
                        'ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at',
                        (key, encoded, datetime.now().isoformat())
                    )
                    self._connection.commit()
                return True
            except Exception as e:
                logging.exception('Write failed for %s (attempt %s): %s', key, attempt + 1, e)
                try:
                    self._connection.rollback()
                except Exception:
                    self._connection = self._connect_database()
                time.sleep(delay)
        raise RuntimeError(f'Failed to write {key}')

    def _write_data(self, key, data):
        """كتابة البيانات إلى SQLite."""
        return self._safe_write(key, data)

    def _mutate_data(self, key, mutation):
        """Atomically read, alter and persist one JSON collection.

        The application deliberately keeps its legacy JSON-in-one-table format.
        Holding the same re-entrant lock across the whole operation prevents a
        second local request from overwriting a concurrent update.
        """
        with self._lock:
            data = self._read_data(key)
            result = mutation(data)
            self._write_data(key, data)
            return result

    def create_backup(self):
        os.makedirs(self.backup_path, exist_ok=True)
        stamp = datetime.now(IRAQ_TZ).strftime('%Y%m%d_%H%M%S')
        if self._backend == 'postgresql':
            if not shutil.which('pg_dump'):
                raise RuntimeError('pg_dump غير مثبت؛ لا يمكن إنشاء نسخة PostgreSQL احتياطية.')
            target = os.path.join(self.backup_path, f'bot4stage_{stamp}.dump')
            try:
                subprocess.run(
                    ['pg_dump', '--format=custom', '--file', target, '--no-owner', self.database_url],
                    check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True,
                )
            except subprocess.CalledProcessError as exc:
                logging.error('PostgreSQL backup failed: %s', exc.stderr.strip())
                if os.path.exists(target):
                    os.unlink(target)
                raise RuntimeError('فشل إنشاء نسخة PostgreSQL الاحتياطية.') from exc
            if not os.path.isfile(target) or os.path.getsize(target) == 0:
                raise RuntimeError('ملف النسخة الاحتياطية فارغ.')
            self._prune_backups('.dump')
            return target

        target = os.path.join(self.backup_path, f'bot_{stamp}.db')
        with self._lock:
            destination = sqlite3.connect(target)
            try:
                if self._backend == 'sqlite':
                    self._connection.backup(destination)
                else:
                    destination.execute('CREATE TABLE app_data (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL)')
                    rows = self._execute('SELECT key, value, updated_at FROM app_data').fetchall()
                    destination.executemany('INSERT INTO app_data(key, value, updated_at) VALUES (?, ?, ?)', rows)
                    destination.commit()
            finally:
                destination.close()
        self._prune_backups('.db')
        return target

    def _prune_backups(self, suffix, keep=7):
        backups = sorted((os.path.join(self.backup_path, name) for name in os.listdir(self.backup_path) if name.endswith(suffix)), key=os.path.getmtime)
        for old_backup in backups[:-keep]:
            os.remove(old_backup)

    def restore_postgres_backup(self, backup_path):
        """Restore a verified custom dump. Intended for an explicit admin CLI flow."""
        if self._backend != 'postgresql':
            raise RuntimeError('الاستعادة عبر pg_restore متاحة لـ PostgreSQL فقط.')
        if not os.path.isfile(backup_path) or not backup_path.endswith('.dump'):
            raise ValueError('ملف النسخة الاحتياطية غير صالح.')
        if not shutil.which('pg_restore'):
            raise RuntimeError('pg_restore غير مثبت.')
        subprocess.run(['pg_restore', '--clean', '--if-exists', '--no-owner', '--dbname', self.database_url, backup_path], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE, text=True)


    def add_user(self, user_id, username, first_name, last_name):
        users = self._read_data('users')
        for user in users:
            if user['user_id'] == user_id:
                user['username'] = username
                user['first_name'] = first_name
                user['last_name'] = last_name
                user['last_active'] = datetime.now().isoformat()
                user['is_new'] = False
                break
        else:
            users.append({
                'user_id': user_id,
                'username': username,
                'first_name': first_name,
                'last_name': last_name,
                'date_joined': datetime.now().isoformat(),
                'last_active': datetime.now().isoformat(),
                'is_new': True,
                'is_banned': False
            })
        self._write_data('users', users)
        return True

    def get_user_stage(self, user_id):
        users_stages = self._read_data('users_stages')
        for user_stage in users_stages:
            if user_stage['user_id'] == user_id:
                return (user_stage['stage'], user_stage['full_name'])
        return None

    def set_user_stage(self, user_id, full_name, stage):
        users_stages = self._read_data('users_stages')
        for user_stage in users_stages:
            if user_stage['user_id'] == user_id:
                user_stage['full_name'] = full_name
                user_stage['stage'] = stage
                user_stage['date_registered'] = datetime.now().isoformat()
                break
        else:
            users_stages.append({
                'user_id': user_id,
                'full_name': full_name,
                'stage': stage,
                'date_registered': datetime.now().isoformat()
            })
        self._write_data('users_stages', users_stages)

        users = self._read_data('users')
        for user in users:
            if user['user_id'] == user_id:
                user['is_new'] = False
                user['last_active'] = datetime.now().isoformat()
                break
        self._write_data('users', users)
        return True

    def update_user_activity(self, user_id):
        users = self._read_data('users')
        for user in users:
            if user['user_id'] == user_id:
                user['last_active'] = datetime.now().isoformat()
                break
        self._write_data('users', users)

    def get_all_users(self):
        users = self._read_data('users')
        return [user['user_id'] for user in users if not user.get('is_banned', False)]

    def get_new_users(self):
        users = self._read_data('users')
        new_users = []
        for user in users:
            if user.get('is_new', False) and not user.get('is_banned', False):
                new_users.append((
                    user['user_id'],
                    user.get('first_name', ''),
                    user.get('last_name', ''),
                    user.get('username', '')
                ))
        return new_users

    def count_users(self):
        users = self._read_data('users')
        return len([user for user in users if not user.get('is_banned', False)])

    def is_banned(self, user_id):
        users = self._read_data('users')
        for user in users:
            if user['user_id'] == user_id:
                return user.get('is_banned', False)
        return False

    def ban_user(self, user_id):
        users = self._read_data('users')
        for user in users:
            if user['user_id'] == user_id:
                user['is_banned'] = True
                self._write_data('users', users)
                return True
        return False

    def unban_user(self, user_id):
        users = self._read_data('users')
        for user in users:
            if user['user_id'] == user_id:
                user['is_banned'] = False
                self._write_data('users', users)
                return True
        return False


    def is_admin(self, user_id):
        admins = self._read_data('admins')
        for admin in admins:
            if admin['user_id'] == user_id:
                return True
        return False

    def add_admin(self, user_id, username, full_name, added_by):
        admins = self._read_data('admins')
        for admin in admins:
            if admin['user_id'] == user_id:
                return False
        admins.append({
            'user_id': user_id,
            'username': username,
            'full_name': full_name,
            'date_added': datetime.now().isoformat(),
            'added_by': added_by
        })
        self._write_data('admins', admins)
        return True

    def remove_admin(self, user_id):
        if user_id == DEVELOPER_ID:
            return False
        admins = self._read_data('admins')
        for i, admin in enumerate(admins):
            if admin['user_id'] == user_id:
                del admins[i]
                self._write_data('admins', admins)
                settings = self._read_data('settings')
                if isinstance(settings, dict):
                    support_admins = settings.get('support_admins', {})
                    settings['support_admins'] = {
                        stage: admin_id for stage, admin_id in support_admins.items()
                        if admin_id != user_id
                    }
                    self._write_data('settings', settings)
                return True
        return False

    def get_admins(self):
        admins = self._read_data('admins')
        return [(admin['user_id'], admin.get('username'), admin.get('full_name')) for admin in admins]

    def set_support_admin(self, stage, admin_id):
        """تعيين أدمن واحد لاستلام تذاكر الدعم لكل مرحلة."""
        if stage not in (1, 2, 3, 4) or not self.is_admin(admin_id):
            return False
        settings = self._read_data('settings')
        if not isinstance(settings, dict):
            settings = {}
        support_admins = settings.get('support_admins', {})
        support_admins[str(stage)] = admin_id
        settings['support_admins'] = support_admins
        self._write_data('settings', settings)
        return True

    def get_support_admin(self, stage):
        settings = self._read_data('settings')
        if not isinstance(settings, dict):
            return None
        admin_id = settings.get('support_admins', {}).get(str(stage))
        return int(admin_id) if admin_id else None


    def get_stage_subjects_by_category(self, stage, category):
        subjects = self._read_data('subjects')
        result = []
        for subject in subjects:
            if subject['stage'] == stage and subject['category'] == category:
                result.append((subject['name_ar'], subject['key']))
        result.sort(key=lambda x: x[0])
        return result

    def get_stage_subject(self, stage, subject_key):
        subjects = self._read_data('subjects')
        for subject in subjects:
            if subject['stage'] == stage and subject['key'] == subject_key:
                return (subject['name_ar'], subject['name_en'], subject['key'], subject['category'])
        return None


    def get_required_channel(self):
        """إرجاع أول قناة للتوافق مع الاستدعاءات القديمة."""
        channels = self.get_required_channels()
        if not channels:
            return None
        _, channel_id, username, title = channels[0]
        return channel_id, username, title

    def get_required_channels(self):
        channels = self._read_data('required_channels')
        return [
            (
                channel.get('id', index),
                channel['channel_id'],
                channel['channel_username'],
                channel['channel_title']
            )
            for index, channel in enumerate(channels, start=1)
        ]

    def add_required_channel(self, channel_id, channel_username, channel_title, added_by):
        channels = self._read_data('required_channels')
        if any(str(channel.get('channel_id')) == str(channel_id) for channel in channels):
            return False

        new_id = max(
            [channel.get('id', index) for index, channel in enumerate(channels, start=1)],
            default=0
        ) + 1
        channels.append({
            'id': new_id,
            'channel_id': channel_id,
            'channel_username': channel_username,
            'channel_title': channel_title,
            'date_added': datetime.now().isoformat(),
            'added_by': added_by
        })
        self._write_data('required_channels', channels)
        return True

    def remove_required_channel(self, record_id):
        channels = self._read_data('required_channels')
        for index, channel in enumerate(channels):
            if channel.get('id', index + 1) == record_id:
                del channels[index]
                self._write_data('required_channels', channels)
                return True
        return False


    def add_search_channel(self, channel_id, channel_username, channel_title, stage, added_by):
        channels = self._read_data('search_channels')
        for channel in channels:
            if channel['channel_id'] == channel_id and channel['stage'] == stage:
                return False

        new_id = max([c.get('id', 0) for c in channels], default=0) + 1

        channels.append({
            'id': new_id,
            'channel_id': channel_id,
            'channel_username': channel_username,
            'channel_title': channel_title,
            'stage': stage,
            'added_by': added_by,
            'date_added': datetime.now().isoformat()
        })
        self._write_data('search_channels', channels)
        return True

    def get_search_channels(self, stage=None):
        channels = self._read_data('search_channels')
        if stage is None:
            return [(channel['id'], channel['channel_username'], channel['channel_title'], channel['stage'])
                    for channel in channels]
        else:
            return [(channel['id'], channel['channel_username'], channel['channel_title'], channel['stage'])
                    for channel in channels if channel['stage'] == stage]

    def remove_search_channel(self, record_id, stage=None):
        channels = self._read_data('search_channels')
        for i, channel in enumerate(channels):
            if channel['id'] == record_id:
                if stage is None or channel['stage'] == stage:
                    del channels[i]
                    self._write_data('search_channels', channels)
                    return True
        return False

    def get_search_channel_by_id(self, record_id):
        channels = self._read_data('search_channels')
        for channel in channels:
            if channel['id'] == record_id:
                return channel
        return None


    def add_support_ticket(self, user_id, message, stage):
        tickets = self._read_data('support_tickets')
        ticket_id = max([t.get('id', 0) for t in tickets], default=0) + 1
        tickets.append({
            'id': ticket_id,
            'user_id': user_id,
            'message': message,
            'stage': stage,
            'date': datetime.now().isoformat()
        })
        self._write_data('support_tickets', tickets)
        return ticket_id

    def get_support_tickets(self):
        tickets = self._read_data('support_tickets')
        result = []
        for ticket in tickets:
            user = self._get_user_by_id(ticket['user_id'])
            if user:
                result.append((
                    ticket['id'],
                    ticket['message'],
                    ticket['stage'],
                    user.get('first_name', ''),
                    user.get('username', ''),
                    ticket['date']
                ))
        result.sort(key=lambda x: x[5], reverse=True)
        return result

    def get_ticket_info(self, ticket_id):
        tickets = self._read_data('support_tickets')
        for ticket in tickets:
            if ticket['id'] == ticket_id:
                user = self._get_user_by_id(ticket['user_id'])
                if user:
                    return (
                        ticket['user_id'],
                        ticket['message'],
                        ticket['stage'],
                        user.get('first_name', ''),
                        user.get('username', ''),
                        ticket['date']
                    )
        return None

    def delete_support_ticket(self, ticket_id):
        tickets = self._read_data('support_tickets')
        for i, ticket in enumerate(tickets):
            if ticket['id'] == ticket_id:
                del tickets[i]
                self._write_data('support_tickets', tickets)
                return True
        return False

    def _get_user_by_id(self, user_id):
        users = self._read_data('users')
        for user in users:
            if user['user_id'] == user_id:
                return user
        return None


    def add_stage_content(self, stage, subject_key, chapter_num, content_type, file_id, file_name=None, text=None, description=None, added_by=None, storage_message_id=None):
        contents = self._read_data('stage_content')
        content_numbers = [c['content_number'] for c in contents
                          if c['stage'] == stage and c['subject_key'] == subject_key and c['chapter_num'] == chapter_num]
        content_number = max(content_numbers) + 1 if content_numbers else 1

        content_id = max([c.get('id', 0) for c in contents], default=0) + 1
        contents.append({
            'id': content_id,
            'stage': stage,
            'subject_key': subject_key,
            'chapter_num': chapter_num,
            'content_type': content_type,
            'file_id': file_id,
            'file_name': file_name,
            'text': text,
            'description': description,
            'added_by': added_by,
            'storage_message_id': storage_message_id,
            'date_added': datetime.now().isoformat(),
            'content_number': content_number
        })
        self._write_data('stage_content', contents)
        # Keep the normalized projection current while legacy callers are
        # gradually moved away from app_data.
        self._execute(
            '''INSERT INTO content(id, stage, subject_key, chapter, content_type, file_id, file_name, body, description, content_number, added_by, storage_message_id)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
               ON CONFLICT(id) DO UPDATE SET description=excluded.description, body=excluded.body, file_name=excluded.file_name''',
            (content_id, stage, subject_key, chapter_num, content_type, file_id, file_name, text, description, content_number, added_by, storage_message_id)
        )
        self._connection.commit()
        return content_id

    def get_stage_content(self, stage, subject_key, chapter_num):
        contents = self._read_data('stage_content')
        result = []
        for content in contents:
            if (content['stage'] == stage and
                content['subject_key'] == subject_key and
                content['chapter_num'] == chapter_num):
                result.append((
                    content['id'],
                    content['content_type'],
                    content['description'],
                    content['date_added'],
                    content['content_number']
                ))
        result.sort(key=lambda x: x[4])
        return result

    def get_stage_content_by_id(self, content_id):
        contents = self._read_data('stage_content')
        for content in contents:
            if content['id'] == content_id:
                return (
                    content['id'],
                    content['stage'],
                    content['subject_key'],
                    content['chapter_num'],
                    content['content_type'],
                    content.get('file_id'),
                    content.get('file_name'),
                    content.get('text'),
                    content.get('description'),
                    content.get('added_by'),
                    content.get('content_number')
                )
        return None

    def get_content_storage_message_id(self, content_id):
        for content in self._read_data('stage_content'):
            if content.get('id') == content_id:
                return content.get('storage_message_id')
        return None

    def update_content_description(self, content_id, description):
        contents = self._read_data('stage_content')
        for content in contents:
            if content['id'] == content_id:
                content['description'] = description
                self._write_data('stage_content', contents)
                self._execute('UPDATE content SET description = ? WHERE id = ?', (description, content_id))
                self._connection.commit()
                return True
        return False

    def delete_stage_content(self, content_id):
        contents = self._read_data('stage_content')
        for i, content in enumerate(contents):
            if content['id'] == content_id:
                del contents[i]
                self._write_data('stage_content', contents)
                self._execute('DELETE FROM content WHERE id = ?', (content_id,))
                self._connection.commit()
                return True
        return False

    def get_all_comments(self):
        comments = self._read_data('comments')
        result = []
        for comment in comments:
            user = self._get_user_by_id(comment['user_id'])
            if user:
                result.append((
                    comment['id'],
                    comment['user_id'],
                    comment['text'],
                    comment['date'],
                    user.get('first_name', ''),
                    user.get('username', ''),
                    comment.get('stage', 1)
                ))
        result.sort(key=lambda x: x[3], reverse=True)
        return result

    def can_user_comment(self, user_id, min_interval_seconds=10):
        """منع السبام: السماح بتعليق واحد كل min_interval_seconds"""
        now = time.time()
        last = self._last_comment_ts.get(user_id, 0)
        if now - last < min_interval_seconds:
            return False
        self._last_comment_ts[user_id] = now
        return True

    def add_comment(self, user_id, content_id, text, stage=None):
        """إضافة تعليق مرتبط بمحتوى محدد مع فحص بسيط لمنع السبام."""
        if not self.can_user_comment(user_id):
            return None

        with self._lock:
            def mutate(comments):
                comment_id = max([c.get('id', 0) for c in comments], default=0) + 1
                comments.append({'id': comment_id, 'user_id': user_id, 'content_id': content_id,
                                 'text': text, 'stage': stage, 'date': datetime.now().isoformat()})
                return comment_id
            comment_id = self._mutate_data('comments', mutate)
            def update_meta(meta):
                record = meta.get(str(content_id), {'count': 0})
                record['count'] = record.get('count', 0) + 1
                meta[str(content_id)] = record
            self._mutate_data('comments_meta', update_meta)
            return comment_id

    def get_comments_for_content(self, content_id):
        comments = self._read_data('comments')
        result = []
        for c in comments:
            if c.get('content_id') == content_id:
                user = self._get_user_by_id(c['user_id']) or {}
                result.append((c['id'], c['user_id'], c['text'], c['date'], user.get('first_name', ''), user.get('username', '')))
        result.sort(key=lambda x: x[3], reverse=False)
        return result

    def delete_comment(self, comment_id, requestor_id=None):
        comments = self._read_data('comments')
        for i, c in enumerate(comments):
            if c['id'] == comment_id:
                if requestor_id is None or requestor_id == c['user_id'] or self.is_admin(requestor_id):
                    del comments[i]
                    self._write_data('comments', comments)
                    meta = self._read_data('comments_meta') or {}
                    key = str(c.get('content_id'))
                    if key in meta:
                        meta[key]['count'] = max(0, meta[key].get('count', 1) - 1)
                        self._write_data('comments_meta', meta)
                    return True
        return False

    def set_ai_enabled(self, enabled):
        """تفعيل أو تعطيل الذكاء الاصطناعي"""
        settings = self._read_data('settings')
        if not isinstance(settings, dict):
            settings = {}
        settings['ai_enabled'] = enabled
        settings['ai_updated'] = datetime.now().isoformat()
        self._write_data('settings', settings)
        return True

    def get_ai_enabled(self):
        """الحصول على حالة الذكاء الاصطناعي"""
        settings = self._read_data('settings')
        if isinstance(settings, dict):
            return settings.get('ai_enabled', False)
        return False

    def set_physics_info_channel(self, channel_id, channel_username, channel_title, added_by):
        """تعيين قناة المعلومات الفيزيائية"""
        channels = [{
            'channel_id': channel_id,
            'channel_username': channel_username,
            'channel_title': channel_title,
            'added_by': added_by,
            'date_added': datetime.now().isoformat()
        }]
        self._write_data('physics_channel', channels)
        return True

    def get_physics_info_channel(self):
        """الحصول على قناة المعلومات الفيزيائية"""
        channels = self._read_data('physics_channel')
        if channels and len(channels) > 0:
            channel = channels[0]
            return (channel['channel_id'], channel['channel_username'], channel['channel_title'])
        return None

    def remove_physics_info_channel(self):
        """إزالة قناة المعلومات الفيزيائية"""
        self._write_data('physics_channel', [])
        return True

    def add_user_physics_info_request(self, user_id, timestamp=None):
        """تسجيل طلب معلومة فيزيائية من المستخدم"""
        requests = self._read_data('physics_requests')
        if not isinstance(requests, list):
            requests = []

        requests.append({
            'user_id': user_id,
            'timestamp': timestamp or datetime.now().isoformat(),
            'delivered': False
        })
        self._write_data('physics_requests', requests)
        return True

    def get_users_eligible_for_physics_info(self, hours_since=24):
        """الحصول على المستخدمين المؤهلين لتلقي معلومة فيزيائية كل 24 ساعة"""
        users_stages = self._read_data('users_stages')
        requests = self._read_data('physics_requests')
        if not isinstance(requests, list):
            requests = []

        now = datetime.now()
        eligible_users = []

        for user_stage in users_stages:
            user_id = user_stage['user_id']

            last_request = None
            for req in sorted(requests, key=lambda x: x['timestamp'], reverse=True):
                if req['user_id'] == user_id:
                    last_request = req
                    break

            if last_request is None:
                eligible_users.append(user_id)
            else:
                last_time = datetime.fromisoformat(last_request['timestamp'])
                if (now - last_time).total_seconds() >= hours_since * 3600:
                    eligible_users.append(user_id)

        return eligible_users

    def count_users_by_stage(self, stage=None):
        """عدد المستخدمين حسب المرحلة"""
        users_stages = self._read_data('users_stages')
        if stage:
            return len([u for u in users_stages if u['stage'] == stage])
        else:
            return len(users_stages)

    def get_users_by_stage(self, stage=None):
        """الحصول على قائمة المستخدمين حسب المرحلة"""
        users_stages = self._read_data('users_stages')
        users = self._read_data('users')

        users_dict = {u['user_id']: u for u in users}

        result = []
        for user_stage in users_stages:
            if stage is None or user_stage['stage'] == stage:
                user_id = user_stage['user_id']
                user_info = users_dict.get(user_id, {})
                result.append({
                    'user_id': user_id,
                    'full_name': user_stage.get('full_name', ''),
                    'stage': user_stage['stage'],
                    'username': user_info.get('username', ''),
                    'first_name': user_info.get('first_name', ''),
                    'last_name': user_info.get('last_name', ''),
                    'date_joined': user_info.get('date_joined', ''),
                    'last_active': user_info.get('last_active', ''),
                    'is_banned': user_info.get('is_banned', False)
                })

        result.sort(key=lambda x: x.get('date_joined', ''), reverse=True)
        return result

    def get_stage_statistics(self):
        """إحصائيات كاملة عن المراحل"""
        users_stages = self._read_data('users_stages')
        users = self._read_data('users')

        stages_count = {1: 0, 2: 0, 3: 0, 4: 0}
        for user_stage in users_stages:
            stage = user_stage['stage']
            if stage in stages_count:
                stages_count[stage] += 1

        total_users = len([u for u in users if not u.get('is_banned', False)])

        today = date.today().isoformat()
        new_users_today = len([u for u in users
                              if u.get('date_joined', '').startswith(today)
                              and not u.get('is_banned', False)])

        active_today = len([u for u in users
                           if u.get('last_active', '').startswith(today)
                           and not u.get('is_banned', False)])

        return {
            'total_users': total_users,
            'new_users_today': new_users_today,
            'active_today': active_today,
            'stage_1': stages_count[1],
            'stage_2': stages_count[2],
            'stage_3': stages_count[3],
            'stage_4': stages_count[4],
            'total_registered': sum(stages_count.values())
        }

    def toggle_favorite(self, user_id, content_id):
        def mutate(favorites):
            match = next((x for x in favorites if x.get('user_id') == user_id and x.get('content_id') == content_id), None)
            if match:
                favorites.remove(match)
                return False
            favorites.append({'user_id': user_id, 'content_id': content_id, 'created_at': datetime.now().isoformat()})
            return True
        return self._mutate_data('favorites', mutate)

    def is_favorite(self, user_id, content_id):
        return any(x['user_id'] == user_id and x['content_id'] == content_id for x in self._read_data('favorites'))

    def get_user_favorites(self, user_id):
        ids = {x['content_id'] for x in self._read_data('favorites') if x['user_id'] == user_id}
        return [self.get_stage_content_by_id(content_id) for content_id in ids if self.get_stage_content_by_id(content_id)]

    def mark_content_viewed(self, user_id, content_id):
        def mutate(progress):
            record = next((x for x in progress if x.get('user_id') == user_id and x.get('content_id') == content_id), None)
            now = datetime.now().isoformat()
            if record:
                record['views'] = record.get('views', 0) + 1
                record['last_viewed'] = now
            else:
                progress.append({'user_id': user_id, 'content_id': content_id, 'views': 1, 'last_viewed': now})
        self._mutate_data('progress', mutate)

    def get_user_progress(self, user_id):
        records = [x for x in self._read_data('progress') if x['user_id'] == user_id]
        attempts = [x for x in self._read_data('quiz_attempts') if x['user_id'] == user_id]
        correct = sum(1 for x in attempts if x.get('correct'))
        return {
            'viewed': len(records),
            'total_views': sum(x.get('views', 0) for x in records),
            'quiz_attempts': len(attempts),
            'quiz_correct': correct,
            'quiz_percent': round(correct * 100 / len(attempts)) if attempts else 0
        }

    def search_content(self, query, stage=None, limit=20):
        """Search in PostgreSQL/SQLite instead of loading all content into Python."""
        limit = max(1, min(int(limit), 100))
        terms = [term for term in query.split() if len(term) > 1]
        if terms:
            clauses = []
            params = []
            for term in terms:
                operator = 'ILIKE' if self._backend == 'postgresql' else 'LIKE'
                clauses.append(f"(c.description {operator} ? OR c.body {operator} ? OR c.file_name {operator} ? OR s.name_ar {operator} ?)")
                params.extend([f'%{term}%'] * 4)
            where = ' AND '.join(clauses)
            if stage is not None:
                where = 'c.stage = ? AND ' + where
                params.insert(0, stage)
            params.append(limit)
            rows = self._execute(
                f'''SELECT c.id, c.stage, c.subject_key, c.chapter, c.content_type,
                           c.file_id, c.file_name, c.body, c.description, c.content_number,
                           c.added_by, s.name_ar
                    FROM content c JOIN subjects s ON (s.stage=c.stage AND s.subject_key=c.subject_key)
                    WHERE {where} ORDER BY c.id DESC LIMIT ?''', params).fetchall()
            if rows:
                return [(
                    {'id': row[0], 'stage': row[1], 'subject_key': row[2], 'chapter_num': row[3],
                     'content_type': row[4], 'file_id': row[5], 'file_name': row[6], 'text': row[7],
                     'description': row[8], 'content_number': row[9], 'added_by': row[10]}, row[11]
                ) for row in rows]

        # Compatibility fallback for data created before the first migration.
        words = [x for x in query.lower().split() if len(x) > 1]
        subjects = {(x['stage'], x['key']): x['name_ar'] for x in self._read_data('subjects')}
        matches = []
        for content in self._read_data('stage_content'):
            if stage and content.get('stage') != stage:
                continue
            subject_name = subjects.get((content.get('stage'), content.get('subject_key')), '')
            haystack = ' '.join(str(content.get(k) or '') for k in ('description', 'text', 'file_name', 'content_type'))
            haystack = f'{haystack} {subject_name}'.lower()
            score = sum(1 for word in words if word in haystack)
            if score:
                matches.append((score, content, subject_name))
        matches.sort(key=lambda x: (x[0], x[1].get('date_added', '')), reverse=True)
        return [(x[1], x[2]) for x in matches[:limit]]

    def add_quiz(self, stage, subject_key, question, options, correct_index, added_by):
        quizzes = self._read_data('quizzes')
        quiz_id = max([x.get('id', 0) for x in quizzes], default=0) + 1
        quizzes.append({
            'id': quiz_id,
            'stage': stage,
            'subject_key': subject_key,
            'question': question,
            'options': options,
            'correct_index': correct_index,
            'added_by': added_by,
            'created_at': datetime.now().isoformat(),
            'enabled': True
        })
        self._write_data('quizzes', quizzes)
        return quiz_id

    def get_random_quiz(self, stage):
        quizzes = [x for x in self._read_data('quizzes') if x.get('enabled', True) and x.get('stage') == stage]
        return random.choice(quizzes) if quizzes else None

    def get_quiz(self, quiz_id):
        return next((x for x in self._read_data('quizzes') if x.get('id') == quiz_id), None)

    def record_quiz_attempt(self, user_id, quiz_id, answer_index):
        with self._lock:
            quiz = self.get_quiz(quiz_id)
            if not quiz or not isinstance(quiz.get('options'), list) or answer_index not in range(len(quiz['options'])):
                return None
            correct = answer_index == quiz.get('correct_index')
            def mutate(attempts):
                attempts.append({'user_id': user_id, 'quiz_id': quiz_id, 'answer_index': answer_index, 'correct': correct, 'created_at': datetime.now().isoformat()})
            self._mutate_data('quiz_attempts', mutate)
            return correct

    def notifications_enabled(self, user_id):
        preferences = self._read_data('notification_preferences')
        return preferences.get(str(user_id), {}).get('enabled', True)

    def toggle_notifications(self, user_id):
        preferences = self._read_data('notification_preferences')
        current = preferences.get(str(user_id), {}).get('enabled', True)
        preferences[str(user_id)] = {'enabled': not current, 'updated_at': datetime.now().isoformat()}
        self._write_data('notification_preferences', preferences)
        return not current

    def schedule_content(self, content_id, publish_at, added_by):
        scheduled = self._read_data('scheduled_content')
        schedule_id = max([x.get('id', 0) for x in scheduled], default=0) + 1
        scheduled.append({'id': schedule_id, 'content_id': content_id, 'publish_at': publish_at, 'added_by': added_by, 'sent': False})
        self._write_data('scheduled_content', scheduled)
        return schedule_id

    def get_due_scheduled_content(self):
        scheduled = self._read_data('scheduled_content')
        now = datetime.now(IRAQ_TZ)
        due = []
        for item in scheduled:
            if item.get('sent'):
                continue
            try:
                publish_at = datetime.fromisoformat(item['publish_at'])
                # Existing rows were stored as Iraq-local naive datetimes.
                if publish_at.tzinfo is None:
                    publish_at = publish_at.replace(tzinfo=IRAQ_TZ)
                if publish_at <= now:
                    due.append(item)
            except (TypeError, ValueError):
                logging.warning('Ignoring scheduled item with invalid date: %s', item.get('id'))
        return due

    def mark_schedule_sent(self, schedule_id):
        scheduled = self._read_data('scheduled_content')
        for item in scheduled:
            if item['id'] == schedule_id:
                item['sent'] = True
                item['sent_at'] = datetime.now().isoformat()
                self._write_data('scheduled_content', scheduled)
                return True
        return False

    def log_action(self, user_id, action, details=None):
        entries = self._read_data('audit_log')
        entries.append({'user_id': user_id, 'action': action, 'details': details or {}, 'created_at': datetime.now().isoformat()})
        self._write_data('audit_log', entries[-5000:])

    def get_learning_statistics(self):
        progress = self._read_data('progress')
        attempts = self._read_data('quiz_attempts')
        return {
            'favorites': len(self._read_data('favorites')),
            'unique_viewers': len({x['user_id'] for x in progress}),
            'content_views': sum(x.get('views', 0) for x in progress),
            'quizzes': len(self._read_data('quizzes')),
            'quiz_attempts': len(attempts),
            'correct_answers': sum(1 for x in attempts if x.get('correct'))
        }

    def get_quiz_leaderboard(self, stage=None, limit=10):
        attempts = self._read_data('quiz_attempts')
        quizzes = {x['id']: x for x in self._read_data('quizzes')}
        scores = {}
        for attempt in attempts:
            quiz = quizzes.get(attempt['quiz_id'])
            if not quiz or (stage and quiz.get('stage') != stage):
                continue
            score = scores.setdefault(attempt['user_id'], {'correct': 0, 'attempts': 0})
            score['attempts'] += 1
            score['correct'] += int(bool(attempt.get('correct')))
        rows = []
        for user_id, score in scores.items():
            user_stage = self.get_user_stage(user_id)
            name = user_stage[1] if user_stage else str(user_id)
            rows.append((user_id, name, score['correct'], score['attempts']))
        rows.sort(key=lambda x: (x[2], x[2] / x[3]), reverse=True)
        return rows[:limit]

db = Database()
